# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firma.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Firma(object):
    def setupUi(self, Firma):
        Firma.setObjectName("Firma")
        Firma.resize(400, 300)
        self.label = QtWidgets.QLabel(Firma)
        self.label.setGeometry(QtCore.QRect(50, 10, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Firma)
        self.pushButton.setGeometry(QtCore.QRect(200, 60, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.btn_ok = QtWidgets.QPushButton(Firma)
        self.btn_ok.setGeometry(QtCore.QRect(100, 250, 113, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(Firma)
        self.btn_cancel.setGeometry(QtCore.QRect(230, 250, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Firma)
        self.pushButton.clicked.connect(Firma.modificato)
        self.btn_ok.clicked.connect(Firma.accetta)
        self.btn_cancel.clicked.connect(Firma.annulla)
        QtCore.QMetaObject.connectSlotsByName(Firma)

    def retranslateUi(self, Firma):
        _translate = QtCore.QCoreApplication.translate
        Firma.setWindowTitle(_translate("Firma", "Form"))
        self.label.setText(_translate("Firma", "Firma is working"))
        self.pushButton.setText(_translate("Firma", "Simula Modifica"))
        self.btn_ok.setText(_translate("Firma", "Accetta"))
        self.btn_cancel.setText(_translate("Firma", "Annulla"))
