# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firma.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Firma(object):
    def setupUi(self, Firma):
        Firma.setObjectName("Firma")
        Firma.resize(1200, 775)
        self.label = QtWidgets.QLabel(Firma)
        self.label.setGeometry(QtCore.QRect(10, -10, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cancel = QtWidgets.QPushButton(Firma)
        self.btn_cancel.setGeometry(QtCore.QRect(1060, 720, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.lista_firma = QtWidgets.QTableWidget(Firma)
        self.lista_firma.setGeometry(QtCore.QRect(10, 50, 1180, 651))
        self.lista_firma.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lista_firma.setAlternatingRowColors(True)
        self.lista_firma.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lista_firma.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lista_firma.setObjectName("lista_firma")
        self.lista_firma.setColumnCount(0)
        self.lista_firma.setRowCount(0)
        self.lista_firma.verticalHeader().setVisible(False)
        self.btn_firma_in_blocco = QtWidgets.QPushButton(Firma)
        self.btn_firma_in_blocco.setGeometry(QtCore.QRect(10, 720, 231, 32))
        self.btn_firma_in_blocco.setObjectName("btn_firma_in_blocco")
        self.alla_data = QtWidgets.QDateEdit(Firma)
        self.alla_data.setGeometry(QtCore.QRect(460, 10, 110, 24))
        self.alla_data.setObjectName("alla_data")
        self.urgenti = QtWidgets.QCheckBox(Firma)
        self.urgenti.setGeometry(QtCore.QRect(640, 10, 87, 22))
        self.urgenti.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.urgenti.setObjectName("urgenti")
        self.label_2 = QtWidgets.QLabel(Firma)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 41, 22))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Firma)
        self.label_4.setGeometry(QtCore.QRect(760, 10, 171, 24))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.diagnostiche = QtWidgets.QComboBox(Firma)
        self.diagnostiche.setGeometry(QtCore.QRect(940, 10, 251, 26))
        self.diagnostiche.setObjectName("diagnostiche")
        self.dalla_data = QtWidgets.QDateEdit(Firma)
        self.dalla_data.setGeometry(QtCore.QRect(260, 10, 110, 24))
        self.dalla_data.setObjectName("dalla_data")
        self.label_3 = QtWidgets.QLabel(Firma)
        self.label_3.setGeometry(QtCore.QRect(400, 10, 41, 22))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Firma)
        self.btn_cancel.clicked.connect(Firma.annulla)
        self.lista_firma.doubleClicked['QModelIndex'].connect(Firma.firma_esame)
        self.btn_firma_in_blocco.clicked.connect(Firma.firma_in_blocco)
        self.dalla_data.editingFinished.connect(Firma.aggiorna_worklist)
        self.alla_data.editingFinished.connect(Firma.aggiorna_worklist)
        self.urgenti.stateChanged['int'].connect(Firma.aggiorna_worklist)
        self.diagnostiche.currentIndexChanged['int'].connect(Firma.aggiorna_worklist)
        QtCore.QMetaObject.connectSlotsByName(Firma)

    def retranslateUi(self, Firma):
        _translate = QtCore.QCoreApplication.translate
        Firma.setWindowTitle(_translate("Firma", "Form"))
        self.label.setText(_translate("Firma", "Worklist di Firma"))
        self.btn_cancel.setText(_translate("Firma", "Esci"))
        self.btn_firma_in_blocco.setText(_translate("Firma", "Firma i Referti Selezionati"))
        self.alla_data.setDisplayFormat(_translate("Firma", "dd/MM/yyyy"))
        self.urgenti.setText(_translate("Firma", "Urgenti"))
        self.label_2.setText(_translate("Firma", "Dal:"))
        self.label_4.setText(_translate("Firma", "Modalità Diagnostiche:"))
        self.dalla_data.setDisplayFormat(_translate("Firma", "dd/MM/yyyy"))
        self.label_3.setText(_translate("Firma", "Al:"))
