# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'richiesta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Richiesta(object):
    def setupUi(self, Dialog_Richiesta):
        Dialog_Richiesta.setObjectName("Dialog_Richiesta")
        Dialog_Richiesta.resize(1000, 700)
        Dialog_Richiesta.setMinimumSize(QtCore.QSize(1000, 700))
        Dialog_Richiesta.setMaximumSize(QtCore.QSize(1000, 700))
        self.btn_ok = QtWidgets.QPushButton(Dialog_Richiesta)
        self.btn_ok.setGeometry(QtCore.QRect(690, 640, 113, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.pushButton = QtWidgets.QPushButton(Dialog_Richiesta)
        self.pushButton.setGeometry(QtCore.QRect(800, 30, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.btn_cancel = QtWidgets.QPushButton(Dialog_Richiesta)
        self.btn_cancel.setGeometry(QtCore.QRect(830, 640, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.label = QtWidgets.QLabel(Dialog_Richiesta)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.descrizione_esame = QtWidgets.QLabel(Dialog_Richiesta)
        self.descrizione_esame.setGeometry(QtCore.QRect(100, 200, 761, 41))
        self.descrizione_esame.setText("")
        self.descrizione_esame.setObjectName("descrizione_esame")

        self.retranslateUi(Dialog_Richiesta)
        self.pushButton.clicked.connect(Dialog_Richiesta.modificato)
        self.btn_ok.clicked.connect(Dialog_Richiesta.accetta)
        self.btn_cancel.clicked.connect(Dialog_Richiesta.annulla)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Richiesta)

    def retranslateUi(self, Dialog_Richiesta):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Richiesta.setWindowTitle(_translate("Dialog_Richiesta", "Richiesta Esame"))
        self.btn_ok.setText(_translate("Dialog_Richiesta", "Accetta"))
        self.pushButton.setText(_translate("Dialog_Richiesta", "Simula Modifica"))
        self.btn_cancel.setText(_translate("Dialog_Richiesta", "Annulla"))
        self.label.setText(_translate("Dialog_Richiesta", "Richiesta is working"))
