# Generated by Django 3.2.3 on 2021-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esame',
            name='stato_avanzamento',
            field=models.IntegerField(choices=[(0, 'Prenotato'), (1, 'Accettato'), (2, 'Schedulato'), (3, 'Iniziato'), (4, 'Completato'), (5, 'Refertato'), (6, 'Firmato'), (7, 'Consegnato'), (8, 'Annullato')], default=0),
        ),
    ]
