# Generated by Django 3.2.3 on 2021-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_esame_stato_avanzamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='anamnesi_remota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='cap',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='citta',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='cognome',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='medico_di_base',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='nome',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='provincia',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='tessera_sanitaria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
