# Generated by Django 3.2.3 on 2021-05-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210530_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paziente',
            name='citta',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='cognome',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='nome',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='paziente',
            name='telefono',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
