# Generated by Django 3.2.3 on 2021-06-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210530_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paziente',
            options={'ordering': ('-cognome', '-nome'), 'verbose_name': 'Paziente', 'verbose_name_plural': 'Pazienti'},
        ),
    ]
