# Generated by Django 3.2.3 on 2021-06-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_paziente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paziente',
            options={'ordering': ('cognome', 'nome'), 'verbose_name': 'Paziente', 'verbose_name_plural': 'Pazienti'},
        ),
    ]
