# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anamnesi_remota.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_anamnesi(object):
    def setupUi(self, Dialog_anamnesi):
        Dialog_anamnesi.setObjectName("Dialog_anamnesi")
        Dialog_anamnesi.resize(500, 300)
        Dialog_anamnesi.setMinimumSize(QtCore.QSize(500, 300))
        Dialog_anamnesi.setMaximumSize(QtCore.QSize(500, 300))
        self.anamnesi_remota = QtWidgets.QPlainTextEdit(Dialog_anamnesi)
        self.anamnesi_remota.setGeometry(QtCore.QRect(10, 10, 481, 231))
        self.anamnesi_remota.setObjectName("anamnesi_remota")
        self.btn_cancel = QtWidgets.QPushButton(Dialog_anamnesi)
        self.btn_cancel.setGeometry(QtCore.QRect(370, 260, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_ok = QtWidgets.QPushButton(Dialog_anamnesi)
        self.btn_ok.setGeometry(QtCore.QRect(240, 260, 113, 32))
        self.btn_ok.setObjectName("btn_ok")

        self.retranslateUi(Dialog_anamnesi)
        self.btn_ok.clicked.connect(Dialog_anamnesi.accept)
        self.btn_cancel.clicked.connect(Dialog_anamnesi.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_anamnesi)

    def retranslateUi(self, Dialog_anamnesi):
        _translate = QtCore.QCoreApplication.translate
        Dialog_anamnesi.setWindowTitle(_translate("Dialog_anamnesi", "Dialog"))
        self.btn_cancel.setText(_translate("Dialog_anamnesi", "Annulla"))
        self.btn_ok.setText(_translate("Dialog_anamnesi", "Salva"))
