# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prestazioni.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Prestazioni(object):
    def setupUi(self, Prestazioni):
        Prestazioni.setObjectName("Prestazioni")
        Prestazioni.resize(811, 641)
        self.btn_ok = QtWidgets.QPushButton(Prestazioni)
        self.btn_ok.setGeometry(QtCore.QRect(530, 580, 113, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(Prestazioni)
        self.btn_cancel.setGeometry(QtCore.QRect(660, 580, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.comboBox_metodica = QtWidgets.QComboBox(Prestazioni)
        self.comboBox_metodica.setGeometry(QtCore.QRect(160, 40, 431, 26))
        self.comboBox_metodica.setObjectName("comboBox_metodica")
        self.comboBox_apparato = QtWidgets.QComboBox(Prestazioni)
        self.comboBox_apparato.setGeometry(QtCore.QRect(160, 70, 431, 26))
        self.comboBox_apparato.setObjectName("comboBox_apparato")
        self.comboBox_organo = QtWidgets.QComboBox(Prestazioni)
        self.comboBox_organo.setGeometry(QtCore.QRect(160, 100, 431, 26))
        self.comboBox_organo.setObjectName("comboBox_organo")
        self.lista_prestazioni = QtWidgets.QTableWidget(Prestazioni)
        self.lista_prestazioni.setGeometry(QtCore.QRect(160, 160, 431, 301))
        self.lista_prestazioni.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lista_prestazioni.setAlternatingRowColors(True)
        self.lista_prestazioni.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lista_prestazioni.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lista_prestazioni.setObjectName("lista_prestazioni")
        self.lista_prestazioni.setColumnCount(0)
        self.lista_prestazioni.setRowCount(0)
        self.lista_prestazioni.verticalHeader().setVisible(False)
        self.label_2 = QtWidgets.QLabel(Prestazioni)
        self.label_2.setGeometry(QtCore.QRect(150, 490, 91, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.modificatore = QtWidgets.QLineEdit(Prestazioni)
        self.modificatore.setGeometry(QtCore.QRect(250, 490, 341, 21))
        self.modificatore.setObjectName("modificatore")
        self.label_3 = QtWidgets.QLabel(Prestazioni)
        self.label_3.setGeometry(QtCore.QRect(60, 40, 91, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Prestazioni)
        self.label_4.setGeometry(QtCore.QRect(60, 70, 91, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Prestazioni)
        self.label_5.setGeometry(QtCore.QRect(60, 100, 91, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Prestazioni)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 141, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Prestazioni)
        self.label_7.setGeometry(QtCore.QRect(150, 540, 91, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.commento = QtWidgets.QLineEdit(Prestazioni)
        self.commento.setGeometry(QtCore.QRect(250, 540, 341, 21))
        self.commento.setObjectName("commento")

        self.retranslateUi(Prestazioni)
        self.btn_ok.clicked.connect(Prestazioni.accetta)
        self.btn_cancel.clicked.connect(Prestazioni.annulla)
        self.comboBox_metodica.currentIndexChanged['int'].connect(Prestazioni.metodica_changed)
        self.comboBox_apparato.currentIndexChanged['int'].connect(Prestazioni.apparato_changed)
        self.comboBox_organo.currentIndexChanged['int'].connect(Prestazioni.organo_changed)
        self.lista_prestazioni.doubleClicked['QModelIndex'].connect(Prestazioni.accetta)
        QtCore.QMetaObject.connectSlotsByName(Prestazioni)

    def retranslateUi(self, Prestazioni):
        _translate = QtCore.QCoreApplication.translate
        Prestazioni.setWindowTitle(_translate("Prestazioni", "Prestazioni"))
        self.btn_ok.setText(_translate("Prestazioni", "Inserisci"))
        self.btn_cancel.setText(_translate("Prestazioni", "Annulla"))
        self.label_2.setText(_translate("Prestazioni", "Modificatori:"))
        self.label_3.setText(_translate("Prestazioni", "Metodica:"))
        self.label_4.setText(_translate("Prestazioni", "Apparato:"))
        self.label_5.setText(_translate("Prestazioni", "Organo:"))
        self.label_6.setText(_translate("Prestazioni", "Prestazioni erogabili:"))
        self.label_7.setText(_translate("Prestazioni", "Commento:"))
