# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Login(object):
    def setupUi(self, Dialog_Login):
        Dialog_Login.setObjectName("Dialog_Login")
        Dialog_Login.resize(1200, 775)
        self.btn_ok = QtWidgets.QPushButton(Dialog_Login)
        self.btn_ok.setGeometry(QtCore.QRect(640, 390, 113, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(Dialog_Login)
        self.btn_cancel.setGeometry(QtCore.QRect(500, 390, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.utente = QtWidgets.QLineEdit(Dialog_Login)
        self.utente.setEnabled(True)
        self.utente.setGeometry(QtCore.QRect(560, 270, 181, 21))
        self.utente.setReadOnly(False)
        self.utente.setObjectName("utente")
        self.label = QtWidgets.QLabel(Dialog_Login)
        self.label.setGeometry(QtCore.QRect(440, 320, 111, 20))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(Dialog_Login)
        self.password.setEnabled(True)
        self.password.setGeometry(QtCore.QRect(561, 320, 181, 21))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setReadOnly(False)
        self.password.setObjectName("password")
        self.label_22 = QtWidgets.QLabel(Dialog_Login)
        self.label_22.setGeometry(QtCore.QRect(460, 270, 81, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")

        self.retranslateUi(Dialog_Login)
        self.btn_ok.clicked.connect(Dialog_Login.accetta)
        self.btn_cancel.clicked.connect(Dialog_Login.annulla)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Login)
        Dialog_Login.setTabOrder(self.utente, self.password)
        Dialog_Login.setTabOrder(self.password, self.btn_ok)
        Dialog_Login.setTabOrder(self.btn_ok, self.btn_cancel)

    def retranslateUi(self, Dialog_Login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Login.setWindowTitle(_translate("Dialog_Login", "Login"))
        self.btn_ok.setText(_translate("Dialog_Login", "Login"))
        self.btn_ok.setShortcut(_translate("Dialog_Login", "Return"))
        self.btn_cancel.setText(_translate("Dialog_Login", "Esci"))
        self.btn_cancel.setShortcut(_translate("Dialog_Login", "Esc"))
        self.label.setText(_translate("Dialog_Login", "Password:"))
        self.label_22.setText(_translate("Dialog_Login", "Utente:"))
