# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferenze.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preferenze(object):
    def setupUi(self, Preferenze):
        Preferenze.setObjectName("Preferenze")
        Preferenze.resize(400, 300)
        self.label = QtWidgets.QLabel(Preferenze)
        self.label.setGeometry(QtCore.QRect(50, 10, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Preferenze)
        self.pushButton.setGeometry(QtCore.QRect(220, 60, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.btn_ok = QtWidgets.QPushButton(Preferenze)
        self.btn_ok.setGeometry(QtCore.QRect(120, 250, 113, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(Preferenze)
        self.btn_cancel.setGeometry(QtCore.QRect(250, 250, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Preferenze)
        self.pushButton.clicked.connect(Preferenze.modificato)
        self.btn_ok.clicked.connect(Preferenze.accetta)
        self.btn_cancel.clicked.connect(Preferenze.annulla)
        QtCore.QMetaObject.connectSlotsByName(Preferenze)

    def retranslateUi(self, Preferenze):
        _translate = QtCore.QCoreApplication.translate
        Preferenze.setWindowTitle(_translate("Preferenze", "Form"))
        self.label.setText(_translate("Preferenze", "Preferenze is working"))
        self.pushButton.setText(_translate("Preferenze", "Simula Modifica"))
        self.btn_ok.setText(_translate("Preferenze", "Accetta"))
        self.btn_cancel.setText(_translate("Preferenze", "Annulla"))
