# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prenotazioni.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Prenotazioni(object):
    def setupUi(self, Prenotazioni):
        Prenotazioni.setObjectName("Prenotazioni")
        Prenotazioni.resize(1200, 800)
        self.label = QtWidgets.QLabel(Prenotazioni)
        self.label.setGeometry(QtCore.QRect(20, -10, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cancel = QtWidgets.QPushButton(Prenotazioni)
        self.btn_cancel.setGeometry(QtCore.QRect(1050, 710, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.calendario = QtWidgets.QCalendarWidget(Prenotazioni)
        self.calendario.setGeometry(QtCore.QRect(30, 100, 1141, 561))
        self.calendario.setObjectName("calendario")
        self.diagnostiche = QtWidgets.QComboBox(Prenotazioni)
        self.diagnostiche.setGeometry(QtCore.QRect(920, 30, 251, 26))
        self.diagnostiche.setObjectName("diagnostiche")
        self.diagnostiche.addItem("")
        self.label_2 = QtWidgets.QLabel(Prenotazioni)
        self.label_2.setGeometry(QtCore.QRect(740, 30, 171, 24))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Prenotazioni)
        self.btn_cancel.clicked.connect(Prenotazioni.annulla)
        QtCore.QMetaObject.connectSlotsByName(Prenotazioni)

    def retranslateUi(self, Prenotazioni):
        _translate = QtCore.QCoreApplication.translate
        Prenotazioni.setWindowTitle(_translate("Prenotazioni", "Form"))
        self.label.setText(_translate("Prenotazioni", "Agenda di Prenotazione"))
        self.btn_cancel.setText(_translate("Prenotazioni", "Esci"))
        self.diagnostiche.setItemText(0, _translate("Prenotazioni", "Tutte le Modalità"))
        self.label_2.setText(_translate("Prenotazioni", "Modalità Diagnostiche:"))
