# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prenotazioni.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Prenotazioni(object):
    def setupUi(self, Prenotazioni):
        Prenotazioni.setObjectName("Prenotazioni")
        Prenotazioni.resize(400, 300)
        self.label = QtWidgets.QLabel(Prenotazioni)
        self.label.setGeometry(QtCore.QRect(50, 10, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cancel = QtWidgets.QPushButton(Prenotazioni)
        self.btn_cancel.setGeometry(QtCore.QRect(260, 250, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.pushButton = QtWidgets.QPushButton(Prenotazioni)
        self.pushButton.setGeometry(QtCore.QRect(230, 60, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.btn_ok = QtWidgets.QPushButton(Prenotazioni)
        self.btn_ok.setGeometry(QtCore.QRect(130, 250, 113, 32))
        self.btn_ok.setObjectName("btn_ok")

        self.retranslateUi(Prenotazioni)
        self.pushButton.clicked.connect(Prenotazioni.modificato)
        self.btn_ok.clicked.connect(Prenotazioni.accetta)
        self.btn_cancel.clicked.connect(Prenotazioni.annulla)
        QtCore.QMetaObject.connectSlotsByName(Prenotazioni)

    def retranslateUi(self, Prenotazioni):
        _translate = QtCore.QCoreApplication.translate
        Prenotazioni.setWindowTitle(_translate("Prenotazioni", "Form"))
        self.label.setText(_translate("Prenotazioni", "Prenotazioni is working"))
        self.btn_cancel.setText(_translate("Prenotazioni", "Annulla"))
        self.pushButton.setText(_translate("Prenotazioni", "Simula Modifica"))
        self.btn_ok.setText(_translate("Prenotazioni", "Accetta"))
