# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controllo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Controllo(object):
    def setupUi(self, Controllo):
        Controllo.setObjectName("Controllo")
        Controllo.resize(400, 300)
        self.label = QtWidgets.QLabel(Controllo)
        self.label.setGeometry(QtCore.QRect(50, 10, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Controllo)
        self.pushButton.setGeometry(QtCore.QRect(210, 60, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.btn_ok = QtWidgets.QPushButton(Controllo)
        self.btn_ok.setGeometry(QtCore.QRect(110, 250, 113, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(Controllo)
        self.btn_cancel.setGeometry(QtCore.QRect(240, 250, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Controllo)
        self.pushButton.clicked.connect(Controllo.modificato)
        self.btn_ok.clicked.connect(Controllo.accetta)
        self.btn_cancel.clicked.connect(Controllo.annulla)
        QtCore.QMetaObject.connectSlotsByName(Controllo)

    def retranslateUi(self, Controllo):
        _translate = QtCore.QCoreApplication.translate
        Controllo.setWindowTitle(_translate("Controllo", "Form"))
        self.label.setText(_translate("Controllo", "Controllo is working"))
        self.pushButton.setText(_translate("Controllo", "Simula Modifica"))
        self.btn_ok.setText(_translate("Controllo", "Accetta"))
        self.btn_cancel.setText(_translate("Controllo", "Annulla"))
