# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controllo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Controllo(object):
    def setupUi(self, Controllo):
        Controllo.setObjectName("Controllo")
        Controllo.resize(1200, 800)
        self.label = QtWidgets.QLabel(Controllo)
        self.label.setGeometry(QtCore.QRect(10, -10, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cancel = QtWidgets.QPushButton(Controllo)
        self.btn_cancel.setGeometry(QtCore.QRect(1060, 720, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.lista_controllo = QtWidgets.QTableWidget(Controllo)
        self.lista_controllo.setGeometry(QtCore.QRect(10, 109, 1180, 601))
        self.lista_controllo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lista_controllo.setAlternatingRowColors(True)
        self.lista_controllo.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lista_controllo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lista_controllo.setObjectName("lista_controllo")
        self.lista_controllo.setColumnCount(0)
        self.lista_controllo.setRowCount(0)
        self.lista_controllo.verticalHeader().setVisible(False)
        self.label_4 = QtWidgets.QLabel(Controllo)
        self.label_4.setGeometry(QtCore.QRect(220, 50, 171, 24))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.diagnostiche = QtWidgets.QComboBox(Controllo)
        self.diagnostiche.setGeometry(QtCore.QRect(400, 50, 251, 26))
        self.diagnostiche.setObjectName("diagnostiche")
        self.alla_data = QtWidgets.QDateEdit(Controllo)
        self.alla_data.setGeometry(QtCore.QRect(480, 10, 110, 24))
        self.alla_data.setObjectName("alla_data")
        self.label_2 = QtWidgets.QLabel(Controllo)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 41, 22))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Controllo)
        self.label_3.setGeometry(QtCore.QRect(420, 10, 41, 22))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(Controllo)
        self.groupBox.setGeometry(QtCore.QRect(770, 5, 391, 81))
        self.groupBox.setObjectName("groupBox")
        self.rb_acc_non_es = QtWidgets.QRadioButton(self.groupBox)
        self.rb_acc_non_es.setGeometry(QtCore.QRect(10, 20, 181, 20))
        self.rb_acc_non_es.setObjectName("rb_acc_non_es")
        self.rb_es_non_ref = QtWidgets.QRadioButton(self.groupBox)
        self.rb_es_non_ref.setGeometry(QtCore.QRect(210, 20, 171, 20))
        self.rb_es_non_ref.setObjectName("rb_es_non_ref")
        self.rb_ref_non_fir = QtWidgets.QRadioButton(self.groupBox)
        self.rb_ref_non_fir.setGeometry(QtCore.QRect(10, 50, 201, 20))
        self.rb_ref_non_fir.setObjectName("rb_ref_non_fir")
        self.dalla_data = QtWidgets.QDateEdit(Controllo)
        self.dalla_data.setGeometry(QtCore.QRect(280, 10, 110, 24))
        self.dalla_data.setObjectName("dalla_data")

        self.retranslateUi(Controllo)
        self.btn_cancel.clicked.connect(Controllo.annulla)
        self.dalla_data.editingFinished.connect(Controllo.aggiorna_worklist)
        self.alla_data.editingFinished.connect(Controllo.aggiorna_worklist)
        self.diagnostiche.currentIndexChanged['int'].connect(Controllo.aggiorna_worklist)
        self.rb_acc_non_es.clicked.connect(Controllo.aggiorna_worklist)
        self.rb_ref_non_fir.clicked.connect(Controllo.aggiorna_worklist)
        self.rb_es_non_ref.clicked.connect(Controllo.aggiorna_worklist)
        QtCore.QMetaObject.connectSlotsByName(Controllo)

    def retranslateUi(self, Controllo):
        _translate = QtCore.QCoreApplication.translate
        Controllo.setWindowTitle(_translate("Controllo", "Form"))
        self.label.setText(_translate("Controllo", "Worklist di Controllo"))
        self.btn_cancel.setText(_translate("Controllo", "Esci"))
        self.label_4.setText(_translate("Controllo", "Modalità Diagnostiche:"))
        self.alla_data.setDisplayFormat(_translate("Controllo", "dd/MM/yyyy"))
        self.label_2.setText(_translate("Controllo", "Dal:"))
        self.label_3.setText(_translate("Controllo", "Al:"))
        self.groupBox.setTitle(_translate("Controllo", "Filtro esami:"))
        self.rb_acc_non_es.setText(_translate("Controllo", "Accettati e non eseguiti"))
        self.rb_es_non_ref.setText(_translate("Controllo", "Eseguiti e non refertati"))
        self.rb_ref_non_fir.setText(_translate("Controllo", "Trascritti e non firmati"))
        self.dalla_data.setDisplayFormat(_translate("Controllo", "dd/MM/yyyy"))
