# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'esame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Esame(object):
    def setupUi(self, Esame):
        Esame.setObjectName("Esame")
        Esame.resize(400, 300)
        self.label = QtWidgets.QLabel(Esame)
        self.label.setGeometry(QtCore.QRect(50, 10, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Esame)
        self.pushButton.setGeometry(QtCore.QRect(200, 60, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.btn_ok = QtWidgets.QPushButton(Esame)
        self.btn_ok.setGeometry(QtCore.QRect(100, 250, 113, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(Esame)
        self.btn_cancel.setGeometry(QtCore.QRect(230, 250, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Esame)
        self.pushButton.clicked.connect(Esame.modificato)
        self.btn_ok.clicked.connect(Esame.accetta)
        self.btn_cancel.clicked.connect(Esame.annulla)
        QtCore.QMetaObject.connectSlotsByName(Esame)

    def retranslateUi(self, Esame):
        _translate = QtCore.QCoreApplication.translate
        Esame.setWindowTitle(_translate("Esame", "Form"))
        self.label.setText(_translate("Esame", "Esame is working"))
        self.pushButton.setText(_translate("Esame", "Simula Modifica"))
        self.btn_ok.setText(_translate("Esame", "Accetta"))
        self.btn_cancel.setText(_translate("Esame", "Annulla"))
