# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'esame.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Esame(object):
    def setupUi(self, Esame):
        Esame.setObjectName("Esame")
        Esame.resize(1200, 775)
        self.label = QtWidgets.QLabel(Esame)
        self.label.setGeometry(QtCore.QRect(10, -10, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cancel = QtWidgets.QPushButton(Esame)
        self.btn_cancel.setGeometry(QtCore.QRect(1060, 720, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")
        self.lista_esecuzione = QtWidgets.QTableWidget(Esame)
        self.lista_esecuzione.setGeometry(QtCore.QRect(10, 50, 1180, 651))
        self.lista_esecuzione.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lista_esecuzione.setAlternatingRowColors(True)
        self.lista_esecuzione.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.lista_esecuzione.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.lista_esecuzione.setObjectName("lista_esecuzione")
        self.lista_esecuzione.setColumnCount(0)
        self.lista_esecuzione.setRowCount(0)
        self.lista_esecuzione.verticalHeader().setVisible(False)
        self.diagnostiche = QtWidgets.QComboBox(Esame)
        self.diagnostiche.setGeometry(QtCore.QRect(940, 10, 251, 26))
        self.diagnostiche.setObjectName("diagnostiche")
        self.label_2 = QtWidgets.QLabel(Esame)
        self.label_2.setGeometry(QtCore.QRect(760, 10, 171, 24))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.btn_aggiorna = QtWidgets.QPushButton(Esame)
        self.btn_aggiorna.setGeometry(QtCore.QRect(30, 720, 113, 32))
        self.btn_aggiorna.setObjectName("btn_aggiorna")

        self.retranslateUi(Esame)
        self.btn_cancel.clicked.connect(Esame.annulla)
        self.lista_esecuzione.doubleClicked['QModelIndex'].connect(Esame.completa_esame)
        self.btn_aggiorna.clicked.connect(Esame.aggiorna_worklist)
        self.diagnostiche.currentIndexChanged['int'].connect(Esame.aggiorna_worklist)
        QtCore.QMetaObject.connectSlotsByName(Esame)

    def retranslateUi(self, Esame):
        _translate = QtCore.QCoreApplication.translate
        Esame.setWindowTitle(_translate("Esame", "Form"))
        self.label.setText(_translate("Esame", "Worklist di Esecuzione"))
        self.btn_cancel.setText(_translate("Esame", "Esci"))
        self.label_2.setText(_translate("Esame", "Modalità Diagnostiche:"))
        self.btn_aggiorna.setText(_translate("Esame", "Aggiorna"))
