# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'refertazione.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Refertazione(object):
    def setupUi(self, Refertazione):
        Refertazione.setObjectName("Refertazione")
        Refertazione.resize(400, 300)
        self.label = QtWidgets.QLabel(Refertazione)
        self.label.setGeometry(QtCore.QRect(50, 10, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Refertazione)
        self.pushButton.setGeometry(QtCore.QRect(220, 60, 131, 32))
        self.pushButton.setObjectName("pushButton")
        self.btn_ok = QtWidgets.QPushButton(Refertazione)
        self.btn_ok.setGeometry(QtCore.QRect(120, 250, 113, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtWidgets.QPushButton(Refertazione)
        self.btn_cancel.setGeometry(QtCore.QRect(250, 250, 113, 32))
        self.btn_cancel.setObjectName("btn_cancel")

        self.retranslateUi(Refertazione)
        self.pushButton.clicked.connect(Refertazione.modificato)
        self.btn_ok.clicked.connect(Refertazione.accetta)
        self.btn_cancel.clicked.connect(Refertazione.annulla)
        QtCore.QMetaObject.connectSlotsByName(Refertazione)

    def retranslateUi(self, Refertazione):
        _translate = QtCore.QCoreApplication.translate
        Refertazione.setWindowTitle(_translate("Refertazione", "Form"))
        self.label.setText(_translate("Refertazione", "Refertazione is working"))
        self.pushButton.setText(_translate("Refertazione", "Simula Modifica"))
        self.btn_ok.setText(_translate("Refertazione", "Accetta"))
        self.btn_cancel.setText(_translate("Refertazione", "Annulla"))
